version: 1.0

system: "base_solospeech_tse_wsj-cfm"

ddim:
  v_prediction: true
  diffusers:
    num_train_timesteps: 1000
    shift: 1.0

diffwrap:
  UDiT:
    in_chans: 256
    out_chans: 128
    embed_dim: 768
    depth: 12
    num_heads: 12
    mlp_ratio: 4.0
    use_checkpoint: false